---
title: "psim"
author: "Mads Cort Nielsen"
date: "2023-09-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(tibble)
library(readr)
library(stringr)
library(ggplot2)
library(forcats)
library(patchwork)
library(scales)
library(tidyverse)
```



### Get data
```{r cars}
# Original
samples_original <- read_delim("../../data/processed/10_datasets/phage_25_fixed_25000/sampletable.tsv", col_names = c("sample_id", "type", "label"), col_types = c("c","c","i"))

# Reduced
samples <- read_delim("../../data/processed/10_datasets/phage_25_fixed_25000_reduced_90/sampletable.tsv", col_names = c("sample_id", "type", "label"), col_types = c("c","c","i"))

# MMseqs2 protein clusters in training split
clusters <- read_delim("../../models/hmm_model/phage_25_reduced_90/pan_proteins/cluster/phage_25_reduced_90.tsv", col_names = c("protein_rep", "protein_id"), delim = "\t")

```

## Manipulate
```{r}
View(samples)

sum_original <- 
  samples_original %>% 
  filter(!str_detect(type, "data")) %>% 
  group_by(type) %>% 
  summarise("count_raw" = n())

sum_reduced <-
  samples %>% 
  filter(!str_detect(type, "data")) %>% 
  group_by(type) %>% 
  summarise("count_reduced_90" = n())

left_join(sum_original, sum_reduced, by = "type") %>% 
  mutate("fraction" = count_reduced_90/count_raw)


```


```{r pressure, echo=FALSE}
sum_reduced %>% 
  ggplot(aes(type,count_reduced_90)) +
  geom_col()
```

```{r}
cluster_sizes <-
  clusters %>% 
  group_by(protein_rep) %>% 
  summarise("cluster_size" = n()) %>% 
  arrange(desc(cluster_size))
cluster_sizes
```

## Visualise taxonomical distribution of satellites

## Load
```{r}
ps_tax <- read_delim("./../../data/processed/01_combined_renamed/ps_tax_info.tsv", delim="\t")

head(ps_tax)
```

```{r}
ps_tax %>% 
  group_by(family) %>% 
  summarise("count" = n())
```


```{r}
ps_tax %>% 
  group_by(family) %>% 
  summarise("count" = n()) %>% 
  count()
```

# BY FAMILY

```{r}
ps_tax %>% 
  group_by(family) %>% 
  summarise("count" = n()) %>% 
  filter(count > 10) %>% 
  count()
```

```{r}
ps_tax %>% 
  group_by(family) %>% 
  summarise("count" = n()) %>% 
  filter(count > 10) %>% 
  ggplot(aes(family,count)) +
  geom_col() +
  coord_flip()
```

# BY GENUS

```{r}
ps_tax %>% 
  group_by(genus) %>% 
  summarise("count" = n()) %>% 
  filter(count > 10) %>% 
  count()
```


```{r}
ps_tax %>% 
  group_by(genus) %>% 
  summarise("count" = n()) %>% 
  filter(count > 10) %>% 
  ggplot(aes(genus,count)) +
  geom_col() +
  coord_flip()
```

# BY SPECIES

```{r}
ps_tax %>% 
  group_by(species) %>% 
  summarise("count" = n()) %>% 
  filter(count > 10) %>% 
  count()
```

```{r}
ps_tax %>% 
  group_by(species) %>% 
  summarise("count" = n()) %>% 
  filter(count > 10) %>% 
  ggplot(aes(species,count)) +
  geom_col() +
  coord_flip()
```
# More than 100
```{r}
ps_tax %>% 
  group_by(species) %>% 
  summarise("count" = n()) %>% 
  filter(count > 50) %>% 
  ggplot(aes(species,count)) +
  geom_col() +
  coord_flip()
```

# Homology reduced sequences

```{r}
ps_90_ids <- read_delim("./../../data/processed/10_datasets/phage_25_fixed_25000_reduced_90_ws/sampletable.tsv", delim="\t", col_names = c('ps_id', 'type', 'label')) %>% 
  filter(label == 1)

ps_tax <- read_delim("./../../data/processed/01_combined_renamed/ps_tax_info.tsv", delim="\t", col_names = TRUE) %>% mutate(ps_id = str_squish(ps_id))


ps_tax
ps_90_ids

```
```{r}
count(ps_90_ids)
```

# Join on homology reduced sampletabl:

```{r}
ps_90 <- semi_join(ps_tax, ps_90_ids, by = join_by(ps_id))
```


# BY FAMILY

```{r}
ps_90 %>% 
  group_by(family) %>% 
  summarise("count" = n())
```

```{r}
ps_90 %>% 
  group_by(family) %>% 
  summarise("count" = n()) %>% 
  filter(count > 10) %>% 
  ggplot(aes(family,count)) +
  geom_col() +
  coord_flip()
```

# BY GENUS

```{r}
ps_90 %>% 
  group_by(genus) %>% 
  summarise("count" = n()) %>% 
  filter(count > 10) %>% 
  count()
```


```{r}
ps_90 %>% 
  group_by(genus) %>% 
  summarise("count" = n()) %>% 
  filter(count > 10) %>% 
  ggplot(aes(genus,count)) +
  geom_col() +
  coord_flip()
```

# BY SPECIES

```{r}
ps_90 %>% 
  group_by(species) %>% 
  summarise() %>% 
  count()
```

```{r}
ps_90 %>% 
  group_by(species) %>% 
  summarise("count" = n()) %>% 
  filter(count >= 50) %>% 
  filter(count < 1000000) %>% 
  select(species)
```

```{r}
ps_90 %>% 
  group_by(species) %>% 
  summarise("count" = n()) %>% 
  filter(count > 10) %>% 
  select(species)
```


```{r}
ps_90 %>% 
  group_by(species) %>% 
  summarise("count" = n()) %>% 
  filter(count > 10) %>% 
  ggplot(aes(species,count)) +
  geom_col() +
  coord_flip()
```
# More than 100
```{r}
ps_90 %>% 
  group_by(species) %>% 
  summarise("count" = n()) %>% 
  filter(count > 50) %>% 
  ggplot(aes(species,count)) +
  geom_col() +
  coord_flip()
```

```{r}
ps_90 %>% 
  group_by(species) %>% 
  summarise() %>% 
  count()
```
# Heatmap of mash distances

# Load data
```{r}
dist <- read_delim("./../../data/visualization/mash_map/mash_dist.tsv", col_names = c("var1","var2","distance", "contig_type"))
```

# Do heatmap
```{r}
dist %>% 
  ggplot(aes(x = var1, y = var2, fill = distance)) +
  geom_tile() +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )
  
```
```{r}
library(forcats)
library(patchwork)
library(scales)

dist <- read_delim("./../../data/visualization/mash_map/mash_dist.tsv", col_names = c("var1","var2","distance", "contig_type"))

# Make var2 an ordered factor based on that order
dist$contig_type <- factor(dist$contig_type, levels = unique(dist$contig_type))
dist$var1 <- factor(dist$var1, levels = unique(dist$var1))
dist$var2 <- factor(dist$var2, levels = unique(dist$var2))

# Determine the order of var2 based on contig_type
ordered_var2 <- dist %>%
  select(var2, contig_type) %>%
  distinct() %>%
  arrange(contig_type, var2) %>%
  pull(var2)

# Make var2 an ordered factor based on that order
dist$var2 <- fct_inorder(dist$var2, ordered_var2)


p2 <- dist %>% 
  ggplot(aes(x = var1, y = var2, fill = distance)) +
  geom_tile() +
  scale_fill_gradientn(colours=c("red", "orange", "white"),
                       values=rescale(c(0, 0.1, 1)),
                       guide="colorbar") +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.margin = margin(0, 0, 0, 0, "pt")
  )

color_strip_data <- dist %>%
  group_by(var2) %>%
  summarise(contig_type = first(contig_type))

# Colorbar plot
p3 <- ggplot(color_strip_data, aes(x = var2, y = 1, fill = contig_type)) +
  geom_tile() +
  coord_fixed(ratio = 1) +
  theme_void() +
  theme(legend.position = "bottom",
        legend.title =  element_blank(),
        plot.margin = margin(0, 0, 0, 0, "pt"))

p1 <- ggplot(color_strip_data, aes(x = 1, y = var2, fill = contig_type)) +
  geom_tile() +
  coord_fixed(ratio = 1) +
  theme_void() +
  theme(legend.position = "none",
        plot.margin = margin(0, 0, 0, 0, "pt"))

p1 + p2 + plot_spacer() + plot_spacer() + p3 + plot_layout(ncol = 3,
                                   widths = c(1, 10),
                                   heights = c(10, 1))

```


```{r}

dist <- read_delim("./../../data/visualization/mash_map/mash_dist_original.tsv", col_names = c("var1","var2","distance", "contig_type"))

# Make var2 an ordered factor based on that order
dist$contig_type <- factor(dist$contig_type, levels = unique(dist$contig_type))
dist$var1 <- factor(dist$var1, levels = unique(dist$var1))
dist$var2 <- factor(dist$var2, levels = unique(dist$var2))

# Determine the order of var2 based on contig_type
ordered_var2 <- dist %>%
  select(var2, contig_type) %>%
  distinct() %>%
  arrange(contig_type, var2) %>%
  pull(var2)

# Make var2 an ordered factor based on that order
dist$var2 <- fct_inorder(dist$var2, ordered_var2)


p2 <- dist %>% 
  ggplot(aes(x = var1, y = var2, fill = distance)) +
  geom_tile() +
  scale_fill_gradientn(colours=c("red", "orange", "white"),
                       values=rescale(c(0, 0.1, 1)),
                       guide="colorbar") +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.margin = margin(0, 0, 0, 0, "pt")
  )

color_strip_data <- dist %>%
  group_by(var2) %>%
  summarise(contig_type = first(contig_type))

# Colorbar plot
p3 <- ggplot(color_strip_data, aes(x = var2, y = 1, fill = contig_type)) +
  geom_tile() +
  coord_fixed(ratio = 1) +
  theme_void() +
  theme(legend.position = "bottom",
        legend.title =  element_blank(),
        plot.margin = margin(0, 0, 0, 0, "pt"))

p1 <- ggplot(color_strip_data, aes(x = 1, y = var2, fill = contig_type)) +
  geom_tile() +
  coord_fixed(ratio = 1) +
  theme_void() +
  theme(legend.position = "none",
        plot.margin = margin(0, 0, 0, 0, "pt"))

p1 + p2 + plot_spacer() + plot_spacer() + p3 + plot_layout(ncol = 3,
                                   widths = c(1, 10),
                                   heights = c(10, 1))

```


```{r}
prediction <- 
  read_delim("./../../data/visualization/sliding_window/predictions.tsv",
             col_names = c("location","refid","tax","truth","prediction","probability")) %>% 
  mutate("truth" = factor(truth)) %>% 
  mutate("prediction" = factor(prediction)) %>% 
  mutate("tax" = factor(tax))
```


```{r}
prediction %>% 
  ggplot(aes(location, sampleid,
             fill = interaction(truth,prediction))) +
  geom_tile()
```


```{r}
prediction %>% 
  ggplot(aes(location, refid,
             fill = interaction(truth,prediction))) +
  geom_tile() +
  scale_fill_manual(values = c("0.0" = "whitesmoke",
                               "1.0" = "dodgerblue",
                               "0.1" = "tomato2",
                               "1.1" = "olivedrab2")) +
  #facet_grid(row = "tax") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title =  element_blank()) +
  facet_wrap(~tax, scales = "free_y", nrow = length(unique(prediction$tax)))
```

```{r}
prediction <- 
  read_delim("./../../data/visualization/sliding_window/predictions.tsv",
             col_names = c("location","refid","tax","truth","prediction","probability")) %>% 
  mutate("truth" = factor(truth)) %>% 
  mutate("prediction" = factor(prediction)) %>% 
  mutate("tax" = factor(tax))

prediction %>% 
  filter(tax == "Escherichia coli") %>% 
  ggplot(aes(location, refid,
             fill = interaction(truth,prediction))) +
  geom_tile() +
  scale_fill_manual(values = c("0.0" = "whitesmoke",
                               "1.0" = "dodgerblue",
                               "0.1" = "tomato2",
                               "1.1" = "olivedrab2")) +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title =  element_blank()) +
  facet_wrap(~tax, scales = "free_y", nrow = length(unique(prediction$tax)))
```


```{r}
prediction <- 
  read_delim("./../../data/visualization/sliding_window/predictions_original.tsv",
             col_names = c("location","refid","tax","truth","prediction","probability")) %>% 
  mutate("truth" = factor(truth)) %>% 
  mutate("prediction" = factor(prediction)) %>% 
  mutate("tax" = factor(tax))

prediction %>% 
  filter(tax == "Escherichia coli") %>% 
  ggplot(aes(location, refid,
             fill = interaction(truth,prediction))) +
  geom_tile() +
  scale_fill_manual(values = c("0.0" = "whitesmoke",
                               "1.0" = "dodgerblue",
                               "0.1" = "tomato2",
                               "1.1" = "olivedrab2")) +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title =  element_blank()) +
  facet_wrap(~tax, scales = "free_y", nrow = length(unique(prediction$tax)))
```


```{r}
prediction <- 
  read_delim("./../../data/visualization/sliding_window/predictions_original.tsv",
             col_names = c("location","refid","tax","truth","prediction","probability")) %>% 
  mutate("truth" = factor(truth)) %>% 
  mutate("prediction" = factor(prediction)) %>% 
  mutate("tax" = factor(tax))

p1 <- prediction %>% 
  filter(tax == "Kocuria palustris") %>% 
  ggplot(aes(location, refid,
             fill = interaction(truth,prediction))) +
  geom_tile() +
  scale_fill_manual(values = c("0.0" = "whitesmoke",
                               "1.0" = "dodgerblue",
                               "0.1" = "tomato2",
                               "1.1" = "olivedrab2")) +
  theme_minimal() +
  theme(legend.position = "none",
        legend.title =  element_blank()) +
  facet_wrap(~tax, scales = "free_y", nrow = length(unique(prediction$tax)))

prediction <- 
  read_delim("./../../data/visualization/sliding_window/predictions.tsv",
             col_names = c("location","refid","tax","truth","prediction","probability")) %>% 
  mutate("truth" = factor(truth)) %>% 
  mutate("prediction" = factor(prediction)) %>% 
  mutate("tax" = factor(tax))

p2 <- prediction %>% 
  filter(tax == "Kocuria palustris") %>% 
  ggplot(aes(location, refid,
             fill = interaction(truth,prediction))) +
  geom_tile() +
  scale_fill_manual(values = c("0.0" = "whitesmoke",
                               "1.0" = "dodgerblue",
                               "0.1" = "tomato2",
                               "1.1" = "olivedrab2")) +
  theme_minimal() +
  theme(legend.position = "none",
        legend.title =  element_blank()) +
  facet_wrap(~tax, scales = "free_y", nrow = length(unique(prediction$tax)))

p1 / p2
```


```{r}
prediction <- 
  read_delim("./../../data/visualization/sliding_window/predictions_version01.tsv",
             col_names = c("location","refid","tax","truth","prediction","probability")) %>% 
  mutate("truth" = factor(truth)) %>% 
  mutate("prediction" = factor(prediction)) %>% 
  mutate("tax" = factor(tax))

prediction %>% 
  filter(tax == "Kosakonia arachidis") %>% 
  ggplot(aes(location, refid,
             fill = interaction(truth,prediction))) +
  geom_tile() +
  scale_fill_manual(values = c("0.0" = "whitesmoke",
                               "1.0" = "dodgerblue",
                               "0.1" = "tomato2",
                               "1.1" = "olivedrab2")) +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title =  element_blank()) +
  facet_wrap(~tax, scales = "free_y", nrow = length(unique(prediction$tax)))
```


## Transformer model:

```{r}
prediction <- 
  read_delim("./../../data/visualization/sliding_window/predictions_version01_transformer.tsv",
             col_names = c("location","refid","tax","truth","prediction","probability")) %>% 
  mutate("truth" = factor(truth)) %>% 
  mutate("prediction" = factor(prediction)) %>% 
  mutate("tax" = factor(tax))

prediction %>% 
  filter(tax == "Escherichia coli") %>% 
  ggplot(aes(location, refid,
             fill = interaction(truth,prediction))) +
  geom_tile() +
  scale_fill_manual(values = c("0.0" = "whitesmoke",
                               "1.0" = "dodgerblue",
                               "0.1" = "tomato2",
                               "1.1" = "olivedrab2")) +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title =  element_blank()) +
  facet_wrap(~tax, scales = "free_y", nrow = length(unique(prediction$tax)))
```




### Marker genes


#### Clustering size distribution:

```{r}
distr <- 
  read_delim("./../../data/processed/10_datasets/attachings/size_dist.tsv",
             col_names = c("protein", "prot_counts"))
```

```{r}
View(distr)
```


```{r}
distr %>% 
  ggplot(aes(x=prot_counts)) +
  geom_histogram()
```

