name: "CNN"

data:
  return_type: "fna"
  pad_pack: False
  use_saved: False

params:
  _target_: src.models.CNN_collection.BasicCNN
  num_classes: 2
  fc_dropout_rate: 0.20
  batchnorm: True
  activation_fn: "ELU"

  fc_num: 1 # number of fully-connected layers after CNN/LSTM
  alt_dropout_rate: 0.0 # dropout on CNNs
  kernel_size_1: 5
  kernel_size_2: 7
  kernel_size_3: 0 # If zero - no third layer.
