name: "BasicInception"

data:
  return_type: "fna"
  pad_pack: False
  use_saved: False

params:
  _target_: src.models.CNN_collection.BasicInception
  num_classes: 2
  fc_dropout_rate: 0.20
  batchnorm: True
  activation_fn: "ELU"
  fc_num: 1 # number of fully-connected layers after CNN/LSTM

  alt_dropout_rate: 0.0 # dropout on CNNs

  num_inception_layers: 2
  out_channels: 16
  kernel_size_b1: 5
  kernel_size_b2: 121
  keep_b3: False
  keep_b4: True
