name: "DeepInception"

data:
  return_type: "fna"
  pad_pack: False
  use_saved: False

params:
  _target_: src.models.CNN_collection.DeepInception
  num_classes: 2
  fc_dropout_rate: 0.25
  batchnorm: True
  activation_fn: "ELU"
  fc_num: 2 # number of fully-connected layers after CNN/LSTM

  alt_dropout_rate: 0.0 # dropout on CNNs

  num_inception_layers: 2
  out_channels: 32
  kernel_size_b1: 7
  kernel_size_b2: 9
  keep_b3: True
  keep_b4: True
