project: "psim"
accelerator: "gpu"
devices: -1
dataset: "dataset_v01"
batch_size: 16
num_workers: 4
epochs: 20
run_group: transformer
run_name: config_test

defaults:
  - model: transformer_profile
  - _self_

optimizer:
  name: "adamw"
  lr: 0.005
