project: "psim"
accelerator: "gpu"
devices: -1
dataset: "dataset_v01"
batch_size: 64
num_workers: 4
epochs: 30
run_group: transformer_sweep_01
run_name: transformer

defaults:
  - model: inception
  - _self_

optimizer:
  name: "adamw"
  lr: 0.001
  warmup: False
