project: "psim"
accelerator: "cuda"
devices: -1
dataset: "phage_25_fixed_25000_reduced_90"
batch_size: 32
num_workers: 8
epochs: 30

model:
  type: "CNN"
  name: "BasicCNN"
  fc_dropout_rate: 0.0
  alt_dropout_rate: 0.0
  fc_num: 4 # number of fully-connected layers after CNN
  conv_num: 3
  kernel_size_1: 5
  kernel_size_2: 7
  batchnorm: False
  activation_fn: "ReLU"

optimizer:
  name: "adam"
  lr: 0.007
