project: "psim"

accelerator: "mps"
devices: 1
dataset: "phage_25_fixed_25000"
batch_size: 16
num_workers: 4
epochs: 4

model:
  type: "CNN"
  name: "SequenceNetGlobalAvg"

optimizer:
  name: "adam"
  lr: 0.007