project: "psim"
accelerator: "gpu"
devices: -1
dataset: "dataset_v01"
batch_size: 64
num_workers: 4
epochs: 100
run_group: transformer_dc
run_name: transformer_alldb

defaults:
  - model: transformer_profile
  - _self_

optimizer:
  name: "adamw"
  lr: 0.0002
  warmup: True
