project: "psim"
accelerator: "gpu"
devices: -1
dataset: "prophage_95_fixed_25000_ps_reduced_90_ws"
batch_size: 16
num_workers: 8
epochs: 1
run_group: cnn
run_name: config_test

defaults:
  - model: cnn
  - _self_

optimizer:
  name: "adamw"
  lr: 0.005
