project: "psim_v02"
accelerator: "gpu"
devices: -1
dataset: "dataset_v02"
batch_size: 32
num_workers: 4
epochs: 30
run_group: deep_inception_v02
run_name: deep_inception

defaults:
  - model: inception
  - _self_

optimizer:
  name: "adamw"
  lr: 0.0025
  warmup: True
