name: inception_sweep
project: psim_v01
program: src/models/LN_train.py
method: bayes
metric:
  goal: maximize
  name: test_f1
parameters:
  batch_size:
    values: [16,32,64]
  optimizer.name:
    values: ["adamw"]
  optimizer.lr:
    values: [0.01,0.005,0.001]
  model.params.fc_dropout_rate:
    values: [0.25]
  model.params.fc_num:
    values: [1,2,3]
  model.params.num_inception_layers:
    values: [1,2,3,5,10]
  model.params.out_channels: 
    values: [8,16,32]
  model.params.kernel_size_b1: 
    values: [3,5,7,9,11,21,31,61,121,241]
  model.params.kernel_size_b2: 
    values: [3,5,7,9,11,21,31,61,121,241]
  model.params.keep_b3: 
    values: [True,False]
  model.params.keep_b4: 
    values: [True,False]
  model.params.batchnorm:
    values: [True]
  model.params.activation_fn:
    values: ["ReLU","ELU"]
command:
  - ${env}
  - python3
  - ${program}
  - ${args_no_hyphens}
