name: test_sweep
project: psim
program: src/models/CNN_train.py
method: bayes
metric:
  goal: maximize
  name: val_acc
parameters:
  batch_size:
    values: [4, 8, 16]
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
