name: test_sweep
project: psim
program: src/models/CNN_train.py
method: bayes
metric:
  goal: maximize
  name: val_acc
parameters:
  batch_size:
    values: [16]
  optimizer:
    values: ["adam", "sgd"]
  model.activation_fn:
    values: ["ReLU", "ELU"] #["ReLU", "LeakyReLU", "PReLU", "ELU"]
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
